### ISSUE TITLE
Initial setup

### ISSUE THREAD

**Issue by 13angs** [13angs/simple-ecom#1]
## Backend
- setup devcontainer for backend (dotnetcore)
  - features: git 
- convert to compose devcontainer
- setup nx workspace
- create product and order services
- fix dev cert error 
- configure swagger ui
- install required packages

```bash
dotnet add package Microsoft.EntityFrameworkCore.InMemory && \
dotnet add package Microsoft.AspNetCore.Mvc.NewtonsoftJson --version 6.0.9 && \
dotnet add package Consul --version 1.6.10.7
```

- create the db context models
- seed the data
- dockerize the services
- setup env in runtime using consul
  - need to use at least 2 consul server
  - need to register/deregister service to consul 
- create gateway service
- configure api gateway using ocelot

```bash
dotnet add package Ocelot --version 18.0.0 && \
dotnet add package Ocelot.Provider.Consul --version 18.0.0
```

- redockerize the services
- deploy using lxd

## References
1. https://developer.hashicorp.com/consul/tutorials/docker/docker-compose-datacenter
2. https://ocelot.readthedocs.io/en/latest/introduction/gettingstarted.html

**Comment by 13angs** [comment]
```bash
Unhandled exception. System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: UntrustedRoot
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at order_sv.Models.SeedData.getProduct() in /workspaces/simple-ecom/backend/apps/order-sv/Models/SeedData.cs:line 22
   at order_sv.Models.SeedData.Seed(IApplicationBuilder app) in /workspaces/simple-ecom/backend/apps/order-sv/Models/SeedData.cs:line 15
   at Program.<Main>$(String[] args) in /workspaces/simple-ecom/backend/apps/order-sv/Program.cs:line 32
dotnet watch ❌ Exited with error code 134
dotnet watch ⏳ Waiting for a file to change before restarting dotnet...
```

**Comment by 13angs** [comment]
When using docker-compose make sure to use `service name` instead of `localhost`

**Comment by 13angs** [comment]
```bash
consul-se-consul-1  | ==> data_dir cannot be empty
```

**Comment by 13angs** [comment]
```bash
failed to sync remote state: error="No cluster leader"
```

**Comment by 13angs** [comment]
```bash
Err: connection error: desc = "transport: Error while dialing dial tcp
```

**Comment by 13angs** [comment]
```bash
Request error: method=GET url=/v1/discovery-chain/se-backend-order-sv?dc=dc1 from=172.27.0.1:52316 error="Connect must be enabled in order to use this endpoint"
```

**Comment by 13angs** [comment]
```bash
Ocelot.Responder.Middleware.ResponderMiddleware[0]
      requestId: 0HMM26N3CDS9D:00000001, previousRequestId: no previous request id, message: Error Code: ConnectionToDownstreamServiceError Message: Error connecting to downstream service, exception: System.Net.Http.HttpRequestException: Resource temporarily unavailable (se-backend-order-sv:5111)
```

**Comment by 13angs** [comment]
```bash
error="Unknown service ID "se-backend-order-sv-v1". Ensure that the service ID is passed, not the service name."
```
