### ISSUE TITLE
Deploy cluster rabbitmq

### ISSUE THREAD

**Issue by 13angs** [13angs/simple-ecom#10]
## Todos
- create two separate rabbitmq cluster
- change the rabbitmq image to `13angs/rabbitmq:3.11.3-management`
- update the rabbitmq.conf to use consul-server
- add separate label for each node

```bash
docker node update --label-add rabbitmq01=true node-1
docker node update --label-add rabbitmq02=true node-2
```

- run the consul and rabbitmq services
- update rabbitmq url in each services

## References
1. https://medium.com/hepsiburadatech/implementing-highly-available-rabbitmq-cluster-on-docker-swarm-using-consul-based-discovery-45c4e7919634

**Comment by 13angs** [comment]
```bash
product_se-backend-product-sv.2.pb319ww9z44p@node-1    | Unhandled exception. RabbitMQ.Client.Exceptions.BrokerUnreachableException: None of the specified endpoints were reachable
product_se-backend-product-sv.2.pb319ww9z44p@node-1    |  ---> RabbitMQ.Client.Exceptions.AuthenticationFailureException: ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.
product_se-backend-product-sv.2.pb319ww9z44p@node-1    |    at RabbitMQ.Client.Framing.Impl.Connection.StartAndTune()
product_se-backend-product-sv.2.pb319ww9z44p@node-1    |    at RabbitMQ.Client.Framing.Impl.Connection.Open(Boolean insist)
product_se-backend-product-sv.2.pb319ww9z44p@node-1    |    at RabbitMQ.Client.Framing.Impl.Connection..ctor(IConnectionFactory factory, Boolean insist, IFrameHandler frameHandler, String clientProvidedName)
product_se-backend-product-sv.2.pb319ww9z44p@node-1    |    at RabbitMQ.Client.Framing.Impl.Connection..ctor(IConnectionFactory factory, Boolean insist, IFrameHandler frameHandler, ArrayPool`1 memoryPool, String clientProvidedName
```
