### ISSUE TITLE
Adding comment and like service

### ISSUE THREAD

**Issue by 13angs** [13angs/simple-ecom#3]
## Steps
- Create new service
- Install the packages

```bash
dotnet add package Microsoft.EntityFrameworkCore.InMemory && \
dotnet add package Microsoft.AspNetCore.Mvc.NewtonsoftJson --version 6.0.9 && \
dotnet add package Consul --version 1.6.10.7
```

- Design and setup the scheme/model
  - dbcontext
  - controller
  - serializer

- install rabbitmq in `common` lib

```bash
dotnet add package RabbitMQ.Client && \
dotnet add package AutoMapper.Extensions.Microsoft.DependencyInjection
```

- Publish the comment
  - product-sv: consume the comment and update the `NComments`

- Connect to consul and update the gateway

## References
1. https://www.mongodb.com/community/forums/t/what-is-the-best-schema-for-a-blog-post-for-storing-the-blog-content-like-share-and-comment/131915

**Comment by 13angs** [comment]
```bash
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at RabbitMQ.Client.IModelExensions.ExchangeDeclare(IModel model, String exchange, String type, Boolean durable, Boolean autoDelete, IDictionary`2 arguments)
   at SeBackend.Common.Services.MessageSubscriber.Subscribe(Func`3 callback) in /workspaces/simple-ecom/backend/libs/SeBackend.Common/Services/MessageSubscriber.cs:line 27
   at product_sv.BgService.DataCollector.StartAsync(CancellationToken cancellationToken) in /workspaces/simple-ecom/backend/apps/product-sv/BgService/DataCollector.cs:line 21
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Microsoft.AspNetCore.Builder.WebApplication.Run(String url)
   at Program.<Main>$(String[] args) in /workspaces/simple-ecom/backend/apps/product-sv/Program.cs:line 56
```
